### ISSUE TITLE
Vue 2 - interaction_in_progress

### ISSUE THREAD

**Issue by ronnierap** [BraedonWooding/msal-vue#4]
When using Vue2 and the simple config.
```main.ts
const msalConfig = {
  auth: {
    clientId: appSettings.sso.clientId,
    authority: appSettings.sso.authority,
    redirectUri: appSettings.sso.redirectUrl,
  },
  cache: {
    cacheLocation: 'localStorage',
  }
}
Vue.use(MsalPlugin, msalConfig)
```

When calling it from a click handler on a button:
```
  public async loginExternal(provider: string, e: Event): Promise<void> {
    console.log('Login with provider', provider, e)
    await this.$msal.loginPopup()
  }
```

It throws the following error when calling 
```
AuthError.js:31 Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js:31:1)
    at new BrowserAuthError (BrowserAuthError.js:201:1)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/error/BrowserAuthError.js.BrowserAuthError.createInteractionInProgressError (BrowserAuthError.js:268:1)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/cache/BrowserCacheManager.js.BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.js:1224:39)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/app/ClientApplication.js.ClientApplication.preflightInteractiveRequest (ClientApplication.js:858:1)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/app/ClientApplication.js.ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.js:843:1)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/app/ClientApplication.js.ClientApplication.acquireTokenPopup (ClientApplication.js:294:1)
    at push../node_modules/msal-vue/node_modules/@azure/msal-browser/dist/app/PublicClientApplication.js.PublicClientApplication.loginPopup (PublicClientApplication.js:81:1)
    at MsalLayer.loginPopup (main.js:19:1)
    at VueComponent.<anonymous> (Login.vue:115:22)
```

Any idea's / thoughts / fixes I need to do?

**Comment by BraedonWooding** [comment]
You can find some information on this here; https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress

There are a few ways this can occur;
1. You don't `await loginPopup` before calling it again, you could console.log prior to calling it and verify it's just being called once.
2. You don't await your loginExternal prior to calling acquireToken.  This is *very* important, you have to wait for the login external to finish (since that is waiting on loginPopup) so for example if you have some vue code like this;

```js
loginExternal();
acquireToken();
```

Then without the awaits this would cause issues.  So make sure your async/awaits are propagated.

Without more context it's hard to give more specific help.  But I do feel pretty certain it won't be related to this library (since it's a light wrapper) and likely is due to the second case above.

**Comment by ronnierap** [comment]
Thanks for the info, I had looked up before what might be the cause on the msal-browser documentation. That's indeed where I saw I forgot to add the await statement on calling loginPopup. ;-) I will await specifically the loginExternal method but it's called from the methods onclick, so the effect will be minimal.

Having logging enabled for msal-browser it now shows this:

```
Login.vue:51 Login with provider test PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0, …}
13:44:08.906 main.ts:83 [Fri, 19 Jan 2024 12:44:08 GMT] : [0ff5e56f-1a32-4e37-ad94-ee3977e34ef3] : @azure/msal-browser@2.38.3 : Verbose - loginPopup called
13:44:08.906 main.ts:83 [Fri, 19 Jan 2024 12:44:08 GMT] : [0ff5e56f-1a32-4e37-ad94-ee3977e34ef3] : @azure/msal-browser@2.38.3 : Verbose - acquireTokenPopup called
13:44:08.907 main.ts:83 [Fri, 19 Jan 2024 12:44:08 GMT] : @azure/msal-browser@2.38.3 : Verbose - preflightBrowserEnvironmentCheck started
13:44:08.907 main.ts:83 [Fri, 19 Jan 2024 12:44:08 GMT] : @azure/msal-browser@2.38.3 : Verbose - preflightInteractiveRequest called, validating app environment
13:44:08.907 AuthError.js:31 Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
...
```

I was thinking: currently I am using 2.38.3 of msal-browser, do we need to downgrade to 2.21.x as specified in the package json?

```
 "@azure/msal-browser": "^2.21",
```

**Comment by ronnierap** [comment]
I must admit one of the trouble shooting steps on the msal-browser pages talked about: if all fails open your application in a new tab. and guess what...

```
main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Verbose - loginPopup called
14:02:47.227 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Verbose - preflightBrowserEnvironmentCheck started
14:02:47.227 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Verbose - acquireTokenPopup called
14:02:47.227 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Verbose - getAllAccounts called
14:02:47.228 main.ts:80 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
14:02:47.228 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - preflightInteractiveRequest called, validating app environment
14:02:47.228 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - initializeAuthorizationRequest called
14:02:47.228 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - getRedirectUri called
14:02:47.229 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Initializing BaseAuthRequest
14:02:47.229 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
14:02:47.230 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - asyncPopup set to false, opening popup before acquiring token
14:02:47.230 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Default popup window width used. Window width not configured or invalid.
14:02:47.230 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Default popup window height used. Window height not configured or invalid.
14:02:47.230 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Default popup window top position used. Window top not configured or invalid.
14:02:47.230 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Default popup window left position used. Window left not configured or invalid.
14:02:47.234 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - acquireTokenPopupAsync called
14:02:47.234 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - initializeServerTelemetryManager called
14:02:47.234 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - initializeAuthorizationRequest called
14:02:47.235 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - getClientConfiguration called
14:02:47.235 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - getDiscoveredAuthority called
14:02:47.235 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Creating discovered authority with request authority
14:02:47.466 Login.vue:62 Fetch finished loading: GET "https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/<code>/oauth2/v2.0/authorize".
...
14:02:47.591 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Auth code client created
14:02:47.592 main.ts:83 [Fri, 19 Jan 2024 13:02:47 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : @azure/msal-common@6.4.0 : Verbose - createAuthCodeUrlQueryString: Prompt is select_account, ignoring account hints
14:02:47.593 main.ts:80 [Fri, 19 Jan 2024 13:02:47 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:popupOpened
14:03:39.097 main.ts:83 [Fri, 19 Jan 2024 13:03:39 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - validateAndExtractStateFromHash called
14:03:39.097 main.ts:83 [Fri, 19 Jan 2024 13:03:39 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - Returning state from hash
14:03:39.097 main.ts:83 [Fri, 19 Jan 2024 13:03:39 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : msal.js.browser@2.21.0 : Verbose - InteractionHandler.handleCodeResponse called
14:03:39.097 main.ts:80 [Fri, 19 Jan 2024 13:03:39 GMT] : [4196f9cc-1ef4-42bb-a32e-6131e3c31de5] : @azure/msal-common@6.4.0 : Info - in acquireToken call
14:03:39.300 Login.vue:62 Fetch failed loading: POST "https://login.microsoftonline.com/<code>/oauth2/v2.0/token".
14:03:39.301 main.ts:80 [Fri, 19 Jan 2024 13:03:39 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
14:03:39.301 AuthError.js:27 Uncaught (in promise) ServerError: invalid_request: 9002326 - [2024-01-19 13:03:39Z]: AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost:8080'. Trace ID: 599481f6-2234-4e72-8989-84f63bae3700 Correlation ID: 135495d2-2eba-455c-9131-f422f2cea832 Timestamp: 2024-01-19 13:03:39Z - Correlation ID: 135495d2-2eba-455c-9131-f422f2cea832 - Trace ID: 599481f6-2234-4e72-8989-84f63bae3700
    at ServerError.AuthError [as constructor] (AuthError.js:27:1)
    at new ServerError (ServerError.js:16:1)
    at push../node_modules/@azure/msal-common/dist/response/ResponseHandler.js.ResponseHandler.validateTokenResponse (ResponseHandler.js:74:1)
    at AuthorizationCodeClient.<anonymous> (AuthorizationCodeClient.js:77:1)
    at step (_tslib.js:75:1)
    at Object.next (_tslib.js:56:45)
    at fulfilled (_tslib.js:46:42)
```
Soo I have now enough info to look further at the MSAL-browser lib. 
Thanks for this great light-weight lib that can easily be introduced into Vue2 and Vue3 apps.

**Comment by BraedonWooding** [comment]
The version of the package shouldn't matter here, I don't expect it to have changed enough to cause something like this.

Is that the only logs?  Cause that would be very suspicious to me, there would almost certainly have to be other logs indicating an interaction is starting.

From looking at other issues seems that it is a potential issue with msal-browser; https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4706.  It may help to just clear your local storage/session storage (or use incognito) to remove any sort of issues with a corrupted login state.

But yeh again, I would need more context to provide any further support/help here, there just isn't enough context, for example I'm not sure if you are calling acquireToken anywhere or if the button onclick is being called/registered twice resulting in a double initialization.

**Comment by BraedonWooding** [comment]
Ah, we posted the comment at the same time!  Yep.  Definitely looks like an issue with the msal-browser package then (or maybe configuration).

Microsoft can be a pain sometimes, best of luck!
